"""esquema inicial muenra vouching

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 04:23:48.769284
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_nit', sa.String(length=30), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('allow_ai_processing', sa.Boolean(), nullable=False),
    sa.Column('allow_training', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)

    op.create_table('document_type_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_type_defs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_type_defs_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('av_status', sa.String(length=30), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('doc_type_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('group_key', sa.String(length=200), nullable=True),
    sa.Column('vouching_status', sa.String(length=40), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_project_id'), ['project_id'], unique=False)

    op.create_table('expected_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('expected_status', sa.String(length=40), nullable=False),
    sa.Column('expected_file', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expected_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_results_project_id'), ['project_id'], unique=False)

    op.create_table('extraction_field_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('doc_types', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_field_defs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_field_defs_project_id'), ['project_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('integrity_report', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('match_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('reconciliation', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_runs_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)

    op.create_table('reference_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('doc_number', sa.String(length=100), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('third_party', sa.String(length=255), nullable=True),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('purchase_order', sa.String(length=100), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('expected_file', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sample_id')
    )
    with op.batch_alter_table('reference_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_items_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_items_project_id'), ['project_id'], unique=False)

    op.create_table('match_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('reference_item_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('allocated_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_item_id'], ['reference_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_links_reference_item_id'), ['reference_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_links_run_id'), ['run_id'], unique=False)

    op.create_table('vouching_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('reference_item_id', sa.Integer(), nullable=False),
    sa.Column('auto_status', sa.String(length=40), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('extracted_number', sa.String(length=100), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_party', sa.String(length=255), nullable=True),
    sa.Column('extracted_nit', sa.String(length=30), nullable=True),
    sa.Column('extracted_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('abs_difference', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_difference', sa.Float(), nullable=True),
    sa.Column('tolerance_applied', sa.Float(), nullable=True),
    sa.Column('name_similarity', sa.Float(), nullable=True),
    sa.Column('nit_match', sa.String(length=30), nullable=True),
    sa.Column('dv_match', sa.String(length=30), nullable=True),
    sa.Column('number_match', sa.String(length=30), nullable=True),
    sa.Column('days_difference', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_page', sa.Integer(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('manual_status', sa.String(length=40), nullable=True),
    sa.Column('review_decision', sa.String(length=20), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_item_id'], ['reference_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['match_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_item_id')
    )
    with op.batch_alter_table('vouching_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouching_results_project_id'), ['project_id'], unique=False)

    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['vouching_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_events_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_events_project_id'))

    op.drop_table('review_events')
    with op.batch_alter_table('vouching_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouching_results_project_id'))

    op.drop_table('vouching_results')
    with op.batch_alter_table('match_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_links_run_id'))
        batch_op.drop_index(batch_op.f('ix_match_links_reference_item_id'))
        batch_op.drop_index(batch_op.f('ix_match_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_match_links_document_id'))

    op.drop_table('match_links')
    with op.batch_alter_table('reference_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_reference_items_import_id'))

    op.drop_table('reference_items')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('match_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_runs_project_id'))

    op.drop_table('match_runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_project_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('extraction_field_defs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_field_defs_project_id'))

    op.drop_table('extraction_field_defs')
    with op.batch_alter_table('expected_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_results_project_id'))

    op.drop_table('expected_results')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_project_id'))

    op.drop_table('entity_aliases')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_documents_group_key'))

    op.drop_table('documents')
    with op.batch_alter_table('document_type_defs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_type_defs_project_id'))

    op.drop_table('document_type_defs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_code'))

    op.drop_table('projects')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
